package com.pavelshapel.aws.spring.boot.starter.api.service;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTransactionWriteExpression;

public interface TransactionWriteExpressionFromSearchCriteriaConverter extends ExpressionFromSearchCriteriaConverter<DynamoDBTransactionWriteExpression> {
}
